services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_DB=api_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: nest-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - DATABASE_URL=postgres://api:development_pass@postgres:5432/api_db

volumes:
  pgdata:
